# Generated by Django 3.2.5 on 2021-07-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReadingAreaNo', models.IntegerField()),
                ('ReadingAreaNM', models.CharField(max_length=20)),
                ('ElectricClaim', models.IntegerField()),
                ('WaterClaim', models.IntegerField()),
                ('GasClaim', models.IntegerField()),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreNO', models.IntegerField()),
                ('StoreType', models.IntegerField()),
                ('StoreNM', models.CharField(max_length=40)),
                ('ElectricBillingYMD', models.DateField(blank=True)),
                ('GasBillingYMD', models.DateField(blank=True)),
                ('WaterBillingYMD', models.DateField(blank=True)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
            ],
            options={
                'unique_together': {('StoreNO', 'ReadingAreaNo')},
            },
        ),
        migrations.CreateModel(
            name='SetPositionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetPositionCD', models.IntegerField()),
                ('SetPositionNM', models.CharField(max_length=20)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
            ],
            options={
                'unique_together': {('SetPositionCD', 'ReadingAreaNo')},
            },
        ),
        migrations.CreateModel(
            name='MeterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeterID', models.IntegerField(unique=True)),
                ('MeterNo', models.IntegerField()),
                ('MeterKBN', models.IntegerField()),
                ('UseType', models.IntegerField()),
                ('Magnification', models.IntegerField()),
                ('CommonType', models.IntegerField()),
                ('ReadingStart', models.IntegerField()),
                ('Remarks', models.CharField(blank=True, max_length=200)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
                ('SetPositionCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.setpositionmaster')),
                ('StoreNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.storemaster')),
            ],
        ),
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeType', models.CharField(max_length=4)),
                ('CodeTypeNM', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=4)),
                ('CodeNM', models.CharField(max_length=20)),
                ('Remarks', models.CharField(blank=True, max_length=30)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('CodeType', 'Code')},
            },
        ),
    ]
