# Generated by Django 3.2.5 on 2021-07-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingArea',
            fields=[
                ('ReadingAreaNo', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('ReadingAreaNM', models.CharField(max_length=20)),
                ('ElectricClaim', models.IntegerField(max_length=1)),
                ('WaterClaim', models.IntegerField(max_length=1)),
                ('GasClaim', models.IntegerField(max_length=1)),
                ('DeleteFlg', models.CharField(max_length=1)),
                ('InsUserID', models.CharField(max_length=20)),
                ('UpdUserID', models.CharField(max_length=20)),
                ('UpdDate', models.DateTimeField()),
            ],
        ),
    ]
