# Generated by Django 3.2.5 on 2021-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingarea',
            name='ElectricClaim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='GasClaim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='ReadingAreaNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='WaterClaim',
            field=models.IntegerField(),
        ),
    ]
