# Generated by Django 3.2.5 on 2021-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210708_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsDate', models.DateTimeField(auto_created=True)),
                ('CodeType', models.CharField(max_length=4)),
                ('CodeTypeNM', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=4)),
                ('CodeNM', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=30)),
                ('DeleteFlg', models.CharField(max_length=1)),
                ('InsUserID', models.CharField(max_length=20)),
                ('UpdUserID', models.CharField(max_length=20)),
                ('UpdDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('CodeType', 'Code')},
            },
        ),
    ]
