# Generated by Django 3.2.5 on 2021-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210716_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storemaster',
            old_name='ReadingArea',
            new_name='ReadingAreaNo',
        ),
        migrations.AlterUniqueTogether(
            name='storemaster',
            unique_together={('StoreNO', 'ReadingAreaNo')},
        ),
    ]
