# Generated by Django 3.2.5 on 2021-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_codemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingarea',
            name='InsUserID',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='UpdDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='UpdUserID',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
