# Generated by Django 3.2.5 on 2021-07-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210708_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemaster',
            name='InsUserID',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='codemaster',
            name='UpdUserID',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
