# Generated by Django 3.2.5 on 2021-07-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_rateshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessingYYYY', models.CharField(default='2021', max_length=4)),
                ('ProcessingMM', models.CharField(default='7', max_length=2)),
                ('ElectricPrice', models.IntegerField()),
                ('GasPrice', models.IntegerField()),
                ('WaterPrice', models.IntegerField()),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
            ],
            options={
                'unique_together': {('ReadingAreaNo', 'ProcessingYYYY', 'ProcessingMM')},
            },
        ),
    ]
