# Generated by Django 3.2.5 on 2021-07-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ElectricAdjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='GasAdjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='WaterAdjustment',
            field=models.IntegerField(default=0),
        ),
    ]
