# Generated by Django 3.2.5 on 2021-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_auto_20210709_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemaster',
            name='DeleteFlg',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='codemaster',
            name='InsUserID',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='codemaster',
            name='Remarks',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='codemaster',
            name='UpdUserID',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='DeleteFlg',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='InsUserID',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='readingarea',
            name='UpdUserID',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
