# Generated by Django 3.2.5 on 2021-07-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20210709_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemaster',
            name='InsDate',
        ),
    ]
