# Generated by Django 3.2.5 on 2021-07-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20210727_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
