# Generated by Django 3.2.5 on 2021-07-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_remove_codemaster_insdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreNO', models.IntegerField()),
                ('StoreType', models.IntegerField()),
                ('StoreNM', models.CharField(max_length=40)),
                ('ElectricBillingYMD', models.DateField(blank=True)),
                ('GasBillingYMD', models.DateField(blank=True)),
                ('WaterBillingYMD', models.DateField(blank=True)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
            ],
        ),
    ]
