# Generated by Django 3.2.5 on 2021-07-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_price_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='Total',
        ),
    ]
