# Generated by Django 3.2.5 on 2021-07-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_remove_price_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReadingYYYY', models.CharField(blank=True, default='2021', max_length=4)),
                ('ProcessingMM', models.CharField(default='7', max_length=2)),
                ('Reading', models.IntegerField()),
                ('Using', models.IntegerField()),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('MeterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.metermaster')),
            ],
            options={
                'unique_together': {('MeterID', 'ReadingYYYY', 'ProcessingMM')},
            },
        ),
    ]
