# Generated by Django 3.2.5 on 2021-07-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_storemaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storemaster',
            old_name='ReadingAreaNM',
            new_name='ReadingAreaNo',
        ),
    ]
