# Generated by Django 3.2.5 on 2021-07-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_rename_readingareanm_storemaster_readingareano'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storemaster',
            unique_together={('StoreNO', 'ReadingAreaNo')},
        ),
    ]
