# Generated by Django 3.2.5 on 2021-07-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_alter_storemaster_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPositionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetPositionCD', models.IntegerField()),
                ('SetPositionNM', models.CharField(max_length=20)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
            ],
            options={
                'unique_together': {('SetPositionCD', 'ReadingAreaNo')},
            },
        ),
        migrations.CreateModel(
            name='MeterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeterID', models.IntegerField(unique=True)),
                ('MeterNo', models.IntegerField()),
                ('MeterKBN', models.IntegerField()),
                ('UseType', models.IntegerField()),
                ('Magnification', models.IntegerField()),
                ('CommonType', models.IntegerField()),
                ('ReadingStart', models.IntegerField()),
                ('Remarks', models.CharField(blank=True, max_length=200)),
                ('DeleteFlg', models.CharField(blank=True, max_length=1)),
                ('InsUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdUserID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('UpdDate', models.DateTimeField(auto_now=True)),
                ('ReadingAreaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.readingarea')),
                ('SetPositionCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.setpositionmaster')),
                ('StoreNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.storemaster')),
            ],
        ),
    ]
